- hosts: all
  become: true
  vars_files:
  - vars/secrets.yml
  roles:
    - mysql
    - wordpress
    - nginx
    - phpmyadmin
  tasks:
    - name: Install make from apt repository
      apt:
        name: make
        state: present

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "/home/alboumed/ansible-cloud-1/srcs/Makefile"
        dest: /home/alboumed