---
# Copy and build nginx container
- name: Include secret variables
  ansible.builtin.include_vars:
    file: ../../../vars/secrets.yml

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/alboumed/ansible-cloud-1/srcs/wordpress
    dest: /home/alboumed
# roles/my_role/tasks/main.yml

- name: Create .env file from template
  template:
    src: ../../../templates/env.j2
    dest: "/home/alboumed/.env"

- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /home/alboumed/data/wp_volume

- name: Create Docker volume for wordpress
  community.docker.docker_volume:
    name: wp_volume
    driver: local
    driver_options:
      type: none
      o: bind
      device: /home/alboumed/data/wp_volume
    state: present

- name: Create a network
  community.docker.docker_network:
    name: mynetwork

- name: Build wordpress docker image
  community.docker.docker_image:
    name: wp_image
    build:
      path: /home/alboumed/wordpress/
    source: build
    state: present

- name: Run wordpress Docker container
  community.docker.docker_container:
    name: wordpress
    image: wp_image
    state: started
    restart_policy: always
    env_file: /home/alboumed/.env
    volumes:
      - "wp_volume:/var/www/html/wordpress"
    networks:
      - name: mynetwork