---
# Copy and build nginx container
- name: Include secret variables
  ansible.builtin.include_vars:
    file: ../../../vars/secrets.yml

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/alboumed
  with_items:
    - "/home/alboumed/ansible-cloud-1/srcs/docker-compose.yml"
    - "/home/alboumed/ansible-cloud-1/srcs/phpmyadmin"

- name: Create .env file from template
  template:
    src: ../../../templates/env.j2
    dest: "/home/alboumed/.env"

- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  with_items:
    - /home/alboumed/data/phpmyadmin_volume

- name: Create and start services
  community.docker.docker_compose_v2:
    build: always
    project_src: /home/alboumed
    services:
      - phpmyadmin