---
- hosts: all
  become: true
  tasks:
    - name: Restart wordpress
      community.docker.docker_compose_v2:
        project_src: /home/alboumed
        services:
          - wordpress
        state: restarted